In [1]:
import pandas as pd

# #Reading Data

In [2]:
df=pd.read_csv('data.csv')

In [3]:
df.head()

,fever,bodypain,age,runnyNose,dryCough,tiredness,diffBreath,headache,sneezing,conjunctivitis,diarrhea,skinRashes,vomting,soreThroat,loss_of_test_or_smell,infectionProb
0,99.317727,0,52,0,-1,1,0,0,0,0,1,0,1,0,1,0
1,99.252250,1,6,1,1,1,-1,0,0,1,1,0,1,1,0,1
2,99.580497,1,19,0,0,1,1,0,0,0,0,0,1,1,1,0
3,100.143119,1,85,1,0,1,0,1,1,1,0,0,0,1,1,1
4,100.276114,1,67,1,-1,0,0,0,1,1,1,0,0,0,0,1

In [4]:
df.tail()

,fever,bodypain,age,runnyNose,dryCough,tiredness,diffBreath,headache,sneezing,conjunctivitis,diarrhea,skinRashes,vomting,soreThroat,loss_of_test_or_smell,infectionProb
1793,100.205960,1,8,0,1,1,0,1,0,1,1,1,1,1,0,1
1794,99.254666,1,30,0,0,0,-1,0,1,1,1,1,1,1,1,1
1795,101.041840,1,65,0,1,0,-1,0,0,0,0,0,0,0,0,1
1796,100.760532,1,65,0,-1,0,-1,0,1,1,0,1,1,1,0,0
1797,101.324957,0,73,0,1,0,0,0,1,0,1,0,1,1,0,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1798 entries, 0 to 1797
Data columns (total 16 columns):
fever                    1798 non-null float64
bodypain                 1798 non-null int64
age                      1798 non-null int64
runnyNose                1798 non-null int64
dryCough                 1798 non-null int64
tiredness                1798 non-null int64
diffBreath               1798 non-null int64
headache                 1798 non-null int64
sneezing                 1798 non-null int64
conjunctivitis           1798 non-null int64
diarrhea                 1798 non-null int64
skinRashes               1798 non-null int64
vomting                  1798 non-null int64
soreThroat               1798 non-null int64
loss_of_test_or_smell    1798 non-null int64
infectionProb            1798 non-null int64
dtypes: float64(1), int64(15)
memory usage: 224.9 KB

In [6]:
df['diffBreath'].value_counts()

 1    616
 0    614
-1    568
Name: diffBreath, dtype: int64

In [7]:
df.describe()

,fever,bodypain,age,runnyNose,dryCough,tiredness,diffBreath,headache,sneezing,conjunctivitis,diarrhea,skinRashes,vomting,soreThroat,loss_of_test_or_smell,infectionProb
count,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000,1798.000000
mean,100.046927,0.499444,50.049499,0.523915,0.010011,0.494438,0.026696,0.512792,0.502225,0.490545,0.496663,0.487764,0.510567,0.487764,0.508899,0.491657
std,1.161595,0.500139,28.583811,0.499567,0.806146,0.500108,0.811272,0.499975,0.500134,0.500050,0.500128,0.499989,0.500027,0.499989,0.500060,0.500069
min,98.001549,0.000000,1.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,99.050036,0.000000,26.000000,0.000000,-1.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,100.079943,0.000000,49.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000
75%,101.068124,1.000000,76.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,101.994244,1.000000,100.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# # Train Test Splitting

In [8]:
import numpy as np

In [9]:
 def data_split(data,ratio):
        np.random.seed(42)
        shuffled= np.random.permutation(len(data))
        test_set_size= int(len(data)*ratio)
        test_indices= shuffled[:test_set_size]
        train_indices= shuffled[test_set_size:]
        return data.iloc[train_indices],data.iloc[test_indices]

In [10]:
np.random.permutation(16)

array([ 7,  2, 11, 13,  6,  8,  4,  1,  5,  3, 14,  9, 15, 10,  0, 12])

In [11]:
train,test = data_split(df,0.2)

In [12]:
train

,fever,bodypain,age,runnyNose,dryCough,tiredness,diffBreath,headache,sneezing,conjunctivitis,diarrhea,skinRashes,vomting,soreThroat,loss_of_test_or_smell,infectionProb
1548,101.180717,1,16,1,0,1,1,1,0,0,1,1,1,0,0,1
1735,99.409491,1,6,0,0,0,-1,1,0,0,1,1,0,1,1,1
855,98.180844,0,15,1,-1,1,-1,0,1,0,0,0,0,0,1,1
1643,100.372598,0,41,1,0,1,1,1,0,1,0,1,1,1,0,1
175,99.269419,1,55,1,1,1,1,0,1,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,98.804620,1,92,0,0,1,1,1,0,1,1,0,1,1,1,1
1294,100.656929,0,16,1,-1,0,1,0,1,1,1,0,1,0,0,0
860,100.145725,1,20,0,1,1,0,1,0,0,0,0,1,0,1,1
1459,100.346410,0,19,0,-1,0,0,0,0,1,1,0,1,0,1,1
1126,98.824630,1,6,0,0,1,0,1,1,1,0,1,0,1,1,0

In [13]:
test

,fever,bodypain,age,runnyNose,dryCough,tiredness,diffBreath,headache,sneezing,conjunctivitis,diarrhea,skinRashes,vomting,soreThroat,loss_of_test_or_smell,infectionProb
1278,101.182913,0,83,1,-1,1,0,0,1,0,1,0,1,1,1,0
220,99.812435,1,80,1,-1,0,0,0,1,1,0,1,0,0,0,0
1519,98.113299,0,90,1,0,1,1,1,0,1,0,0,0,0,1,0
438,100.285538,0,42,0,-1,1,1,0,1,1,0,0,1,1,0,0
1271,98.721607,1,70,0,-1,1,1,0,1,0,0,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1523,98.259920,1,61,0,0,0,0,1,1,0,1,1,1,1,1,1
1732,99.534091,0,17,1,0,0,0,1,1,1,1,0,1,1,1,0
1631,100.832971,1,31,0,-1,0,-1,0,0,1,1,1,1,0,0,1
1037,99.933826,0,24,1,1,1,0,1,0,1,1,1,0,1,1,0
965,98.589559,1,73,1,-1,0,0,0,0,0,1,1,0,0,0,1

In [14]:
X_train= train[['fever','bodypain','age','runnyNose','dryCough','tiredness','diffBreath','headache','sneezing','conjunctivitis','diarrhea','skinRashes','vomting','soreThroat','loss_of_test_or_smell','infectionProb']].to_numpy()
X_test= test[['fever','bodypain','age','runnyNose','dryCough','tiredness','diffBreath','headache','sneezing','conjunctivitis','diarrhea','skinRashes','vomting','soreThroat','loss_of_test_or_smell','infectionProb']].to_numpy()

In [15]:
Y_train= train[['infectionProb']].to_numpy().reshape(1439,)
Y_test= test[['infectionProb']].to_numpy().reshape(359,)

In [16]:
Y_train

array([1, 1, 1, ..., 1, 1, 0], dtype=int64)

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
clf= LogisticRegression()
clf.fit(X_train,Y_train)

C:\Users\ykris\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
inputFeatures =[98,0,38,1,1,-1,1,0,1,0,0,1,1,0,0,0]
infProb= clf.predict_proba([inputFeatures])[0]

In [20]:
infProb

array([0.98839098, 0.01160902])